In [57]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [58]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [59]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [60]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [61]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [62]:
df2=df.sample(frac=1)

In [63]:
df2.shape

(569, 31)

In [64]:
hold_on_data=df2.iloc[0:285,:]

In [65]:
hold_on_data.shape

(285, 31)

In [66]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
382        12.05         22.72           78.75      447.8          0.06935   
154        13.15         15.34           85.31      538.9          0.09384   
512        13.40         20.52           88.64      556.7          0.11060   
347        14.76         14.74           94.87      668.7          0.08875   
478        11.49         14.59           73.99      404.9          0.10460   
..           ...           ...             ...        ...              ...   
456        11.63         29.29           74.87      415.1          0.09357   
546        10.32         16.35           65.31      324.9          0.09434   
16         14.68         20.13           94.74      684.5          0.09867   
312        12.76         13.37           82.29      504.1          0.08794   
232        11.22         33.81           70.79      386.8          0.07780   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
382           0.10730        0.079430             0.029780         0.1203   
154           0.08498        0.092930             0.034830         0.1822   
512           0.14690        0.144500             0.081720         0.2116   
347           0.07780        0.046080             0.035280         0.1521   
478           0.08228        0.053080             0.019690         0.1779   
..                ...             ...                  ...            ...   
456           0.08574        0.071600             0.020170         0.1799   
546           0.04994        0.010120             0.005495         0.1885   
16            0.07200        0.073950             0.052590         0.1586   
312           0.07948        0.040520             0.025480         0.1601   
232           0.03574        0.004967             0.006434         0.1845   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
382                 0.06659  ...          28.71            87.36       488.4   
154                 0.06207  ...          20.50            97.67       677.3   
512                 0.07325  ...          29.66           113.30       844.4   
347                 0.05912  ...          17.93           114.20       880.8   
478                 0.06574  ...          21.90            82.04       467.6   
..                      ...  ...            ...              ...         ...   
456                 0.06166  ...          38.81            86.04       527.8   
546                 0.06201  ...          21.77            71.12       384.9   
16                  0.05922  ...          30.88           123.40      1138.0   
312                 0.06140  ...          16.40            92.04       618.8   
232                 0.05828  ...          41.78            78.44       470.9   

     worst smoothness  worst compactness  worst concavity  \
382           0.08799            0.32140          0.29120   
154           0.14780            0.22560          0.30090   
512           0.15740            0.38560          0.51060   
347           0.12200            0.20090          0.21510   
478           0.13520            0.20100          0.25960   
..                ...                ...              ...   
456           0.14060            0.20310          0.29230   
546           0.12850            0.08842          0.04384   
16            0.14640            0.18710          0.29140   
312           0.11940            0.22080          0.17690   
232           0.09994            0.06885          0.02318   

     worst concave points  worst symmetry  worst fractal dimension  target  
382               0.10920          0.2191                  0.09349       1  
154               0.09722          0.3849                  0.08633       1  
512               0.20510          0.3585                  0.11090       0  
347               0.12510          0.3109                  0.08187       1  
478               0.07431          0.2941                  0.091

In [67]:
df1=df2.iloc[286:569,:]

In [68]:
y=df1.iloc[:,-1]

In [69]:
y

480    1
466    1
85     0
192    1
152    1
      ..
551    1
340    1
334    1
329    0
448    1
Name: target, Length: 283, dtype: int64

In [70]:
X=df1.iloc[:,:-1]

In [71]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
480       12.160         18.03           78.29      455.3          0.09087   
466       13.140         20.74           85.98      536.9          0.08675   
85        18.460         18.52          121.10     1075.0          0.09874   
192        9.720         18.22           60.73      288.1          0.06950   
152        9.731         15.34           63.78      300.2          0.10720   
..           ...           ...             ...        ...              ...   
551       11.130         22.44           71.49      378.4          0.09566   
340       14.420         16.54           94.15      641.2          0.09751   
334       12.300         19.02           77.88      464.4          0.08313   
329       16.260         21.88          107.50      826.8          0.11650   
448       14.530         19.34           94.25      659.7          0.08388   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
480           0.07838        0.029160             0.015270         0.1464   
466           0.10890        0.108500             0.035100         0.1562   
85            0.10530        0.133500             0.087950         0.2132   
192           0.02344        0.000000             0.000000         0.1653   
152           0.15990        0.410800             0.078570         0.2548   
..                ...             ...                  ...            ...   
551           0.08194        0.048240             0.022570         0.2030   
340           0.11390        0.080070             0.042230         0.1912   
334           0.04202        0.007756             0.008535         0.1539   
329           0.12830        0.179900             0.079810         0.1869   
448           0.07800        0.088170             0.029250         0.1473   

     mean fractal dimension  ...  worst radius  worst texture  \
480                 0.06284  ...        13.340          27.87   
466                 0.06020  ...        14.800          25.46   
85                  0.06022  ...        22.930          27.68   
192                 0.06447  ...         9.968          20.83   
152                 0.09296  ...        11.020          19.49   
..                      ...  ...           ...            ...   
551                 0.06552  ...        12.020          28.26   
340                 0.06412  ...        16.670          21.51   
334                 0.05945  ...        13.350          28.46   
329                 0.06532  ...        17.730          25.21   
448                 0.05746  ...        16.300          28.39   

     worst perimeter  worst area  worst smoothness  worst compactness  \
480            88.83       547.4           0.12080            0.22790   
466           100.90       689.1           0.13510            0.35490   
85            152.20      1603.0           0.13980            0.20890   
192            62.25       303.8           0.07117            0.02729   
152            71.04       380.5           0.12920            0.27720   
..               ...         ...               ...                ...   
551            77.80       436.6           0.10870            0.17820   
340           111.40       862.1           0.12940            0.33710   
334            84.53       544.3           0.12220            0.09052   
329           113.70       975.2           0.14260            0.21160   
448           108.10       830.5           0.10890            0.26490   

     worst concavity  worst concave points  worst symmetry  \
480          0.16200               0.05690          0.2406   
466          0.45040               0.11810          0.2563   
85           0.31570               0.16420          0.3695   
192          0.00000               0.00000          0.1909   
152          0.82160               0.15710          0.3108   
..               ...                   ...             ...   
551          0.15640               0.06413         

In [72]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [73]:
X

array([[-0.54707688, -0.30234505, -0.55284897, ..., -0.83233936,
        -0.75035949, -0.34895365],
       [-0.24807227,  0.31379325, -0.21210537, ...,  0.11818182,
        -0.49404786, -0.1139913 ],
       [ 1.37509561, -0.19093997,  1.34406049, ...,  0.83417898,
         1.35400796,  0.09985084],
       ...,
       [-0.50436193, -0.07726132, -0.57101606, ..., -1.09746022,
        -0.50874088, -0.6245724 ],
       [ 0.70386078,  0.57298059,  0.74144501, ..., -0.08993883,
        -0.2116153 , -0.23068047],
       [ 0.17602611, -0.00450698,  0.15433802, ..., -0.22599383,
        -0.64424321, -0.48940305]])

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [75]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [76]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [77]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
382        12.05         22.72           78.75      447.8          0.06935   
154        13.15         15.34           85.31      538.9          0.09384   
512        13.40         20.52           88.64      556.7          0.11060   
347        14.76         14.74           94.87      668.7          0.08875   
478        11.49         14.59           73.99      404.9          0.10460   
..           ...           ...             ...        ...              ...   
456        11.63         29.29           74.87      415.1          0.09357   
546        10.32         16.35           65.31      324.9          0.09434   
16         14.68         20.13           94.74      684.5          0.09867   
312        12.76         13.37           82.29      504.1          0.08794   
232        11.22         33.81           70.79      386.8          0.07780   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
382           0.10730        0.079430             0.029780         0.1203   
154           0.08498        0.092930             0.034830         0.1822   
512           0.14690        0.144500             0.081720         0.2116   
347           0.07780        0.046080             0.035280         0.1521   
478           0.08228        0.053080             0.019690         0.1779   
..                ...             ...                  ...            ...   
456           0.08574        0.071600             0.020170         0.1799   
546           0.04994        0.010120             0.005495         0.1885   
16            0.07200        0.073950             0.052590         0.1586   
312           0.07948        0.040520             0.025480         0.1601   
232           0.03574        0.004967             0.006434         0.1845   

     mean fractal dimension  ...  worst radius  worst texture  \
382                 0.06659  ...         12.57          28.71   
154                 0.06207  ...         14.77          20.50   
512                 0.07325  ...         16.41          29.66   
347                 0.05912  ...         17.27          17.93   
478                 0.06574  ...         12.40          21.90   
..                      ...  ...           ...            ...   
456                 0.06166  ...         13.12          38.81   
546                 0.06201  ...         11.25          21.77   
16                  0.05922  ...         19.07          30.88   
312                 0.06140  ...         14.19          16.40   
232                 0.05828  ...         12.36          41.78   

     worst perimeter  worst area  worst smoothness  worst compactness  \
382            87.36       488.4           0.08799            0.32140   
154            97.67       677.3           0.14780            0.22560   
512           113.30       844.4           0.15740            0.38560   
347           114.20       880.8           0.12200            0.20090   
478            82.04       467.6           0.13520            0.20100   
..               ...         ...               ...                ...   
456            86.04       527.8           0.14060            0.20310   
546            71.12       384.9           0.12850            0.08842   
16            123.40      1138.0           0.14640            0.18710   
312            92.04       618.8           0.11940            0.22080   
232            78.44       470.9           0.09994            0.06885   

     worst concavity  worst concave points  worst symmetry  \
382          0.29120               0.10920          0.2191   
154          0.30090               0.09722          0.3849   
512          0.51060               0.20510          0.3585   
347          0.21510               0.12510          0.3109   
478          0.25960               0.07431          0.2941   
..               ...                   ...             ...   
456          0.29230               0.06835         

In [78]:
h_X=sc.fit_transform(h_X)

In [79]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [80]:
x1

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [81]:
x2

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [82]:
x3

array([1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [83]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [84]:
df4=df3.T

In [85]:
df4

0  1  2
0    1  1  1
1    1  1  1
2    0  0  0
3    1  1  1
4    1  1  1
..  .. .. ..
280  1  1  1
281  1  1  1
282  0  0  0
283  1  1  1
284  1  1  1

[285 rows x 3 columns]

In [86]:
lr2=LogisticRegression()

In [87]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [88]:
df4_X

0  1  2
0    1  1  1
1    1  1  1
2    0  0  0
3    1  1  1
4    1  1  1
..  .. .. ..
280  1  1  1
281  1  1  1
282  0  0  0
283  1  1  1
284  1  1  1

[285 rows x 3 columns]

In [89]:
df4_Y

382    1
154    1
512    0
347    1
478    1
      ..
456    1
546    1
16     0
312    1
232    1
Name: target, Length: 285, dtype: int64

In [90]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [91]:
X_test=sc.fit_transform(X_test)

In [92]:
X_test

array([[ 2.09793963,  0.25527788,  2.05463383, ...,  0.7298783 ,
         0.46240688, -1.10618958],
       [-0.77668242, -0.55580718, -0.76135112, ..., -0.24156749,
        -0.82638253, -0.28634269],
       [ 0.39360523,  1.45495354,  0.50802077, ...,  1.39200801,
         1.86409562,  0.98080213],
       ...,
       [-1.43863667, -0.14896065, -1.42979442, ..., -1.12940127,
         0.42072097, -0.13564874],
       [ 1.50125776, -0.67055876,  1.41779316, ...,  0.82815059,
        -0.10382674,  0.13165364],
       [ 0.10350575, -0.82182221,  0.11298803, ...,  0.40928508,
         0.17234241,  0.31583515]])

In [93]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [94]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [95]:
df6=df5.T

In [96]:
df6

0  1  2
0   0  0  0
1   1  1  1
2   0  0  0
3   1  1  1
4   0  1  0
.. .. .. ..
89  0  1  0
90  1  0  0
91  1  0  1
92  0  0  0
93  1  1  0

[94 rows x 3 columns]

In [97]:
df6_X=df6.iloc[:,:]


In [98]:
final=lr2.predict(df6_X)

In [99]:
from sklearn.metrics import accuracy_score

In [100]:
accuracy_score(y_test, final)


0.9361702127659575

In [101]:
precision = precision_score(y_test, final, average=None)
recall = recall_score(y_test, final, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.97222222 0.9137931 ]
recall: [0.875      0.98148148]


In [102]:
from sklearn.ensemble import StackingClassifier

In [103]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [104]:
df_X=sc.fit_transform(df_X)

In [105]:
df_X.shape

(569, 30)

In [106]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [107]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [108]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [109]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [110]:
final1=clf.predict(df_X_test)

In [111]:
accuracy_score(df_y_test, final1)

0.9840425531914894

In [112]:
precision = precision_score(df_y_test, final1, average=None)
recall = recall_score(df_y_test, final1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.97014925 0.99173554]
recall: [0.98484848 0.98360656]
