# 1_NB_Classifier_Weather

In [46]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [47]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

In [48]:
#create labelEncoder
le = preprocessing.LabelEncoder()

#converting string labels into numbers
weather_encoded = le.fit_transform(weather)
print("Weather :",weather_encoded)

temp_encoded = le.fit_transform(temp)
print("Temp :",temp_encoded)

label = le.fit_transform(play)
print("Play :",label)

Weather : [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp : [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play : [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [49]:
#combining weather and temp into single listof tuple
features = tuple(zip(weather_encoded,temp_encoded))
print("Features :",features)

Features : ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [50]:
#create classifier
model = MultinomialNB()

#train the model using the training sets
model.fit(features,label)

MultinomialNB()

In [51]:

#predict output
predicted = model.predict([[0,1]]) #0:overcast,1:Hot
print("Predicted Value:",predicted)

predicted= model.predict([[2,2]]) #2:Sunny, 2:Mild
print("Predicted Value:", predicted)

Predicted Value: [1]
Predicted Value: [1]


# 2_NB_Classifier_Iris

In [52]:
import numpy as np
from sklearn import datasets

#Load dataset
iris = datasets.load_iris()

In [53]:
print("Features :",iris.feature_names)
print("\nLabels :",iris.target_names)
print("\nData Shape: ",iris.data.shape)
print("\nData: ",iris.data)
print("\nTarget Shape: ",iris.target.shape)
print("\nTarget: ",iris.target)
print("\nData Type: ",type(iris.data))

newdata = iris.data[50:,:]
newtarget = iris.target[50:]

print("\nNew Data Shape: ",newdata.shape)
print("\nNew Target Shape: ",newtarget.shape)

Features : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Labels : ['setosa' 'versicolor' 'virginica']

Data Shape:  (150, 4)

Data:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.

In [54]:
from sklearn.model_selection import train_test_split

data_train,data_test,target_train,target_test = train_test_split(newdata,newtarget,test_size=0.30,random_state=53)

In [55]:
gnb = GaussianNB()
gnb.fit(data_train,target_train)
target_pred = gnb.predict(data_test)

In [56]:
from sklearn import metrics
print("Accuracy: ",metrics.accuracy_score(target_test,target_pred))

Accuracy:  0.9666666666666667


In [57]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test,target_pred)

array([[13,  0],
       [ 1, 16]])

In [58]:
from sklearn.metrics import precision_score,recall_score
precision = precision_score(target_test,target_pred)
print('pricision: {}'.format(precision))
recall = recall_score(target_test,target_pred)
print('recall: {}'.format(recall))

pricision: 0.9285714285714286
recall: 1.0


# 3_NB_Classifier_Iris

# Task - 1

In [59]:
import pandas as pd
import numpy as np
import io
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.naive_bayes import GaussianNB,MultinomialNB


In [60]:
# from google.colab import files
# uploaded = files.upload()
# datasets = pd.read_csv(io.BytesIO(uploaded['Dataset2.csv']))
datasets = pd.read_csv("Dataset2.csv")

FileNotFoundError: ignored

In [ ]:
datasets

In [ ]:
le = LabelEncoder()
X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,-1].values

In [ ]:
outlook_encoded=le.fit_transform(X[:,0])

In [ ]:
outlook_encoded

In [ ]:
temp_encoded=le.fit_transform(X[:,1])

In [ ]:
temp_encoded

In [ ]:
Wind_encoded=le.fit_transform(X[:,2])

In [ ]:
Wind_encoded

In [ ]:
humidity_encoded=le.fit_transform(X[:,3])

In [ ]:
humidity_encoded

In [ ]:
Y

In [ ]:
features= np.array(list(zip(outlook_encoded,temp_encoded,Wind_encoded,humidity_encoded)),dtype=object)

print("Features: ", features)
print("Target: ",Y)

In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(features,
Y, test_size = 0.1, random_state = 53)
print(data_train.shape,target_train.shape)

In [ ]:
data_test

In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Nor-
mal’, and Wind = ’False’?**bold text**

In [ ]:
pre=[1,2,2,0]
np.array(pre).reshape(1,-1)

In [ ]:
gnb.predict(np.array(pre).reshape(1,-1))

In [ ]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?**bold text**

In [ ]:
pre=[2,0,0,1]
np.array(pre).reshape(1,-1)

In [ ]:
gnb.predict(np.array(pre).reshape(1,-1))

In [ ]:
gnb.predict_proba(np.array(pre).reshape(1,-1))

# Task:2

In [ ]:
import sklearn
from sklearn import datasets
digit_data = sklearn.datasets.load_digits();
features = digit_data.feature_names
targets = digit_data.target_names
print(digit_data.feature_names)

In [ ]:
df=pd.DataFrame(digit_data.data, columns=digit_data.feature_names)
df["target"]=pd.Series(digit_data.target)

In [ ]:
df.head()

In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(digit_data.data,
digit_data.target, test_size = 0.35, random_state = 53)
print(data_test)
data_train

In [ ]:
import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)
target_pred

In [ ]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))